name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --parallel 4

    - name: Upload artifacts (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: dumpsource2-linux
        path: build/DumpSource2-*

    - name: Upload artifacts (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: dumpsource2-windows
        path: build/Debug/DumpSource2-*.exe
